# Generated by Django 2.0.3 on 2018-03-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.TextField(unique=True)),
                ('patient_id', models.TextField()),
                ('doctor_id', models.TextField()),
                ('booked_on', models.DateTimeField()),
                ('on_date', models.DateField()),
                ('estimated_time', models.DateTimeField()),
                ('fees_paid', models.BooleanField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('speciality', models.TextField()),
                ('fees', models.IntegerField()),
                ('contact_no', models.TextField(unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('experience', models.IntegerField()),
                ('age', models.IntegerField()),
                ('degree', models.TextField(null=True)),
                ('doctor_terminal_login', models.TextField()),
                ('doctor_terminal_password', models.TextField()),
                ('independent_doctor', models.BooleanField()),
                ('address', models.TextField()),
                ('appointment_list', models.ManyToManyField(blank=True, to='Content.Appointments')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('contact_no', models.TextField(unique=True)),
                ('appointment_list', models.ManyToManyField(blank=True, to='Content.Appointments')),
            ],
        ),
    ]
