# Generated by Django 2.0.3 on 2018-04-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='booking_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='estimated_time',
            field=models.DateTimeField(null=True),
        ),
    ]
