# Generated by Django 2.0.3 on 2018-04-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_auto_20180409_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='estimated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
