# Generated by Django 2.0.3 on 2018-04-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0003_auto_20180409_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo_url',
            field=models.TextField(blank=True),
        ),
    ]
