# Generated by Django 2.0.3 on 2018-04-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0005_patient_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='current_appointment_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
